### PR TITLE
fix: process cron updates directly

### LINKED ISSUE #65: Stop adding hidden comment to update issues
Currently, to trigger an update within a given repository, the plugin adds an hidden comment to the issue, which in turn triggers the comment edited workflow within the repo. It works fine, bur on the long term the issue contains lots of garbage hidden content, since each update add content to that issue.

Instead, we should directly spawn an octokit instance which has the proper authentication and directly acts on the repository, to avoid creating content spam like we do now.

### PR DESCRIPTION
**Pull request by gentlementlegen**
Resolves #65
QA: https://github.com/Meniole/daemon-merging/actions/runs/21351044644

QA (E2E 2026-01-27):
- Kernel configured to run Meniole/daemon-merging@fix/dispatch-e2e-20260127.
- Target repo: Meniole/daemon-merging-e2e-20260127.
- Created issue #1 and PR #2 (linked via "Fixes #1").
- App approval added, waited >1 minute, then edited the issue to trigger the scan.
- Result: PR #2 auto-merged at 2026-01-27T17:22:36Z.
- Compute run logs: https://github.com/Meniole/daemon-merging/actions/runs/21407144970.
- Evidence: https://github.com/Meniole/daemon-merging-e2e-20260127/pull/2.

### CODE REVIEW

**Comment by gentlementlegen** [comment]
@codex review

File: src/cron/index.ts [hunk 1]
```diff
@@ -12,6 +17,61 @@ let rateWindowStart = Date.now();
...
+  }
+
+  if (!privateKey.trim()) {
+    throw new Error("APP_PRIVATE_KEY is missing.");
+  }
+
+  return { appId, privateKey };
+}
+
+async function getInstallationOctokit(appOctokit: Context["octokit"], owner: string, repo: string) {
```
Comment (0x4007) [inline src/cron/index.ts]: Also this

File: src/cron/index.ts [hunk 2]
```diff
@@ -12,6 +17,61 @@ let rateWindowStart = Date.now();
...
+    authStrategy: createAppAuth,
+    auth: {
+      appId,
+      privateKey,
+      installationId: installation.data.id,
+    },
+  });
+}
+
+async function resolveRepoConfig(octokit: Context["octokit"], owner: string, repo: string): Promise<PluginSettings | null> {
```
Comment (0x4007) [inline src/cron/index.ts]: Pretty sure this is?

**Review by 0x4007 — CHANGES_REQUESTED** [review]
Pretty sure this should all be loaded from our SDK

File: src/cron/index.ts [hunk 3]
```diff
@@ -12,6 +17,61 @@ let rateWindowStart = Date.now();
 let rateProcessed = 0;
 const logger = new Logs(process.env.LOG_LEVEL ?? "info");
 
+function normalizeMultilineSecret(value: string): string {
+  return value.includes("\\n") ? value.replace(/\\n/g, "\n") : value;
+}
+
+function getAppAuth() {
```
[the remark this answers is not in the document]
Comment (gentlementlegen) [reply src/cron/index.ts]: This just normalizes the env variables for good measure

**Review by 0x4007 — APPROVED** [review]
